language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'

before_script:
  - npm prune

script:
  - npm run lint
  - npm run test:headless

after_success:
  - npm run coveralls
  - npm run build_prod
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
