language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

before_script:
  - npm prune

after_success:
  - npm run build_prod
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
